SkrzypekjanShop/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SkrzypekjanShop.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Photo { get; set; }
        public double Price { get; set; }
    }
}

SkrzypekjanShop/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SkrzypekjanShop.Models;

namespace SkrzypekjanShop.Controllers
{
    public class BasketController : Controller
    {

        private static List<Product> basket = new List<Product>();
        List<Product> products = ProductController.products;
        private static double basketPrice;
        
        // GET: Basket
        public ActionResult Index()
        {
            Math.Round(basketPrice, 2, MidpointRounding.AwayFromZero);
            ViewBag.basketPrice = "Total price: " + String.Format("{0:0.00}", basketPrice);
            return View(basket);
        }

        public ActionResult Message()
        {
            return View();
        }

        // GET: Basket/Add
        public ActionResult Add(int id)
        {
            try
            {
                var product = products.FirstOrDefault(x => x.ProductId == id);
                basketPrice += product.Price;
                basket.Add(product);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(basket);
            }
        }

        // GET: BasketController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                var product = products.FirstOrDefault(x => x.ProductId == id);
                basketPrice -= product.Price;
                basket.Remove(product);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(basket);
            }
        }
    }
}

SkrzypekjanShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SkrzypekjanShop.Models;

namespace SkrzypekjanShop.Controllers
{
    public class ProductController : Controller
    {

        public static List<Product> products = new List<Product>()
        {
                new Product(){ ProductId = 1, Name = "T-shirt", Photo = "https://a.allegroimg.com/s512/03a495/6b2048ee4c3297c67532a2af90ae/KOSZULKA-T-SHIRT-MESKA-JHK-TSRA-150-CZARNA-XXL", Price = 16.20 },
                new Product(){ ProductId = 2, Name = "Trousers", Photo = "https://contents.mediadecathlon.com/p298255/ke8f7eea4f12af3b78b529dc7a0923f11/298255_default.jpg?format=auto&quality=60&f=800x0", Price = 15.50 },
                new Product(){ ProductId = 3, Name = "Cap", Photo = "https://az1.hatstoremedia.com/hatstore/images/4978_1/652/522/0/adjustable-black-basic-cap.jpg", Price = 9.90 },
                new Product(){ ProductId = 4, Name = "Blouse", Photo = "https://st2.depositphotos.com/4192645/6758/i/450/depositphotos_67585779-stock-photo-white-hoodie-design.jpg", Price = 20.20 },
                new Product(){ ProductId = 5, Name = "Shorts", Photo = "https://marvel-b1-cdn.bc0a.com/f00000000058595/cdn.shopify.com/s/files/1/0077/0432/products/Khakinators_5_LD_frontweb_400x.progressive.jpg?v=1596760301", Price = 12.90 },
                new Product(){ ProductId = 6, Name = "Sweater", Photo = "https://static.pullandbear.net/2/photos/2020/I/0/1/p/9553/351/804/9553351804_1_1_3.jpg?t=1603984271617", Price = 22.20 },
                new Product(){ ProductId = 7, Name = "T-shirt", Photo = "https://a.allegroimg.com/s512/03a495/6b2048ee4c3297c67532a2af90ae/KOSZULKA-T-SHIRT-MESKA-JHK-TSRA-150-CZARNA-XXL", Price = 16.20 },
                new Product(){ ProductId = 8, Name = "Trousers", Photo = "https://contents.mediadecathlon.com/p298255/ke8f7eea4f12af3b78b529dc7a0923f11/298255_default.jpg?format=auto&quality=60&f=800x0", Price = 15.50 },
                new Product(){ ProductId = 9, Name = "Cap", Photo = "https://az1.hatstoremedia.com/hatstore/images/4978_1/652/522/0/adjustable-black-basic-cap.jpg", Price = 9.90 },
                new Product(){ ProductId = 10, Name = "Blouse", Photo = "https://st2.depositphotos.com/4192645/6758/i/450/depositphotos_67585779-stock-photo-white-hoodie-design.jpg", Price = 20.20 },
                new Product(){ ProductId = 11, Name = "Shorts", Photo = "https://marvel-b1-cdn.bc0a.com/f00000000058595/cdn.shopify.com/s/files/1/0077/0432/products/Khakinators_5_LD_frontweb_400x.progressive.jpg?v=1596760301", Price = 12.90 },
                new Product(){ ProductId = 12, Name = "Sweater", Photo = "https://static.pullandbear.net/2/photos/2020/I/0/1/p/9553/351/804/9553351804_1_1_3.jpg?t=1603984271617", Price = 22.20 },
                new Product(){ ProductId = 13, Name = "T-shirt", Photo = "https://a.allegroimg.com/s512/03a495/6b2048ee4c3297c67532a2af90ae/KOSZULKA-T-SHIRT-MESKA-JHK-TSRA-150-CZARNA-XXL", Price = 16.20 },
                new Product(){ ProductId = 14, Name = "Trousers", Photo = "https://contents.mediadecathlon.com/p298255/ke8f7eea4f12af3b78b529dc7a0923f11/298255_default.jpg?format=auto&quality=60&f=800x0", Price = 15.50 },
                new Product(){ ProductId = 15, Name = "Cap", Photo = "https://az1.hatstoremedia.com/hatstore/images/4978_1/652/522/0/adjustable-black-basic-cap.jpg", Price = 9.90 },
                new Product(){ ProductId = 16, Name = "Blouse", Photo = "https://st2.depositphotos.com/4192645/6758/i/450/depositphotos_67585779-stock-photo-white-hoodie-design.jpg", Price = 20.20 },
                new Product(){ ProductId = 17, Name = "Shorts", Photo = "https://marvel-b1-cdn.bc0a.com/f00000000058595/cdn.shopify.com/s/files/1/0077/0432/products/Khakinators_5_LD_frontweb_400x.progressive.jpg?v=1596760301", Price = 12.90 },
                new Product(){ ProductId = 18, Name = "Sweater", Photo = "https://static.pullandbear.net/2/photos/2020/I/0/1/p/9553/351/804/9553351804_1_1_3.jpg?t=1603984271617", Price = 22.20 }
        };

        // GET: Product
        public ActionResult Index()
        {
            return View(products);
        }

        // GET: Product/Buy/5
        public ActionResult Buy(int id)
        {
            return View(products.FirstOrDefault(x => x.ProductId == id));
        }
    }
}

SkrzypekjanShop/Views/Basket/Index.cshtml
@model IEnumerable<SkrzypekjanShop.Models.Product>

@{
    ViewData["Title"] = "Index";
    string basketPrice = ViewBag.basketPrice;
}

<div class="container div-buy">
    <br />
    <div class="my-shadow spacings">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Photo)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Price)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            <img src="@item.Photo" width="200" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Price)$
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = item.ProductId }, new { @class = "btn btn-danger" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <h3>@Html.Raw(basketPrice)$</h3>

        <a class="btn btn-warning" asp-controller="Product" asp-action="Index">Back to List</a>
        <a class="btn btn-success" asp-controller="Basket" asp-action="Message">Confirm purchases</a>
    </div>
    <br />
</div>

SkrzypekjanShop/Views/Basket/Message.cshtml
@model SkrzypekjanShop.Models.Product

@{
    ViewData["Title"] = "Message";
}

<div class="container div-buy">
    <br />
    <div class="my-shadow spacings">
        <h1>Thank you for shopping in our store!</h1>

        <div>
            <h4>
                This website is for educational purposes only. You won't buy these items here, but it shows how a online-shop works.
            </h4>
        </div>
        <div>
            <a class="btn btn-warning" asp-controller="Product" asp-action="Index">Back to List</a>
        </div>
    </div>
    <br />
</div>

SkrzypekjanShop/Views/Product/Buy.cshtml
@model SkrzypekjanShop.Models.Product

@{
    ViewData["Title"] = "Buy";
}



<div class="container div-buy">
    <br />
    <div class="my-shadow spacings">
        <h1>Buy product</h1>
        <h4>Product</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Photo)
            </dt>
            <dd class="col-sm-10">
                <img src="@Model.Photo" width="400" />
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Price)$
            </dd>
        </dl>
        <div class="spacings">
               @Html.ActionLink("Add to basket", "Add", "Basket" , new { id=Model.ProductId }, new { @class="btn btn-primary" })
            <a class="btn btn-warning" asp-action="Index">Back to List</a>
        </div>
    </div>
    <br />
</div>

SkrzypekjanShop/Views/Product/Index.cshtml
@model IEnumerable<SkrzypekjanShop.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<div class="container-fluid" style="width:95%">
    <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-sm-3 mx-auto my-shadow div-buy">
                    <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
                    <p><img class="img-fluid" src="@item.Photo" /></p>
                    <h4 class="price-position">@Html.DisplayFor(modelItem => item.Price)$</h4>
                    <p class="btn-position">@Html.ActionLink("Buy", "Buy", new { id = item.ProductId }, new { @class = "btn btn-primary" })</p>
                </div>
            }
    </div>
</div>

SkrzypekjanShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SkrzypekjanShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body style="padding-top: 56px; background-color:grey;">
    <header>
        <nav class="navbar fixed-top navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Index">SkrzypekjanShop</a>
                <div>
                    <a class="btn btn-dark" asp-controller="Product" asp-action="Index">Back to shop</a>
                    <a class="btn btn-danger" asp-controller="Basket" asp-action="Index">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-basket3" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM3.394 15l-1.48-6h-.97l1.525 6.426a.75.75 0 0 0 .729.574h9.606a.75.75 0 0 0 .73-.574L15.056 9h-.972l-1.479 6h-9.21z" />
                        </svg>
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid div-color">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid p-2 bg-dark text-white">
            &copy; 2020 - SkrzypekjanShop @*- <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>